vectorcloud/main/models.py
from vectorcloud import db


class Files(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())
    path = db.Column(db.String())
    external_path = db.Column(db.String())
    cache = db.Column(db.String())
    folder = db.Column(db.String())


class PluginStorage(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    plugin = db.Column(db.String())
    entry_type = db.Column(db.String())
    value_json = db.Column(db.String())
    vector_id = db.Column(db.Integer)


class Vectors(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    serial = db.Column(db.String())
    cert_file = db.Column(db.String())
    ip = db.Column(db.String())
    name = db.Column(db.String())
    guid = db.Column(db.String())
    custom_name = db.Column(db.String())
    description = db.Column(db.String())


class Repositories(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String())
    name = db.Column(db.String())
    fp = db.Column(db.String())
    auto_update = db.Column(db.String())


db.create_all()
db.session.commit()

vectorcloud/main/__init__.py
#!/usr/bin/env python3

vectorcloud/main/routes.py
import os
import glob
from secrets import token_hex
from htmlmin.main import minify
from flask import (
    render_template,
    url_for,
    redirect,
    request,
    Blueprint,
    jsonify,
)
from flask_login import current_user
from vectorcloud.main.models import Files, Vectors, Repositories
from vectorcloud.main.utils import (
    run_plugin,
    get_repositories,
    get_plugins,
    uninstall_plugin,
    install_plugin,
    add_repository,
    delete_repository,
    update_repositories,
    reinstall_plugin,
    trigger_reload,
)
from vectorcloud.paths import cache_folder
from vectorcloud import app, db


main = Blueprint("main", __name__)


# ------------------------------------------------------------------------------
# intial routes and functions (before/after request)
# ------------------------------------------------------------------------------
@app.after_request
def response_minify(response):
    """
    minify html response to decrease site traffic
    """
    if response.content_type == "text/html; charset=utf-8":
        response.set_data(minify(response.get_data(as_text=True)))

        return response
    return response


# blocks access to all pages (except public routes) unless the user is
# signed in.
@main.before_app_request
def check_valid_login():

    if "/api/" in request.path:
        return
    elif current_user.is_authenticated:
        return
    elif getattr(app.view_functions[request.endpoint], "is_public", False):
        return
    elif request.endpoint.startswith("static"):
        return

    else:
        return redirect(url_for("user_system.login"))


# ------------------------------------------------------------------------------
# /home
# ------------------------------------------------------------------------------
@main.route("/")
@main.route("/home", methods=["GET", "POST"])
def home():
    vectors = Vectors.query.all()

    plugins, plugin_icons, plugin_panels, plugins_js = get_plugins()

    return render_template(
        "main/home.html",
        vectors=vectors,
        plugins=plugins,
        plugin_icons=plugin_icons,
        plugin_panels=plugin_panels,
        plugins_js=plugins_js,
        restart_needed=os.environ.get("VC_RESTART_NEEDED", None),
    )


@main.route("/load_repositories", methods=["GET"])
def load_repositories():
    repositories = get_repositories()
    return render_template("main/repositories.html", repositories=repositories)


@main.route("/run", methods=["POST"])
def run():
    options = {}
    for fieldname, value in request.form.items():
        if fieldname != "plugin_name" and len(value) >= 1:
            options[fieldname] = value
    return run_plugin(request.form.get("plugin_name"), options)


@main.route("/delete_plugin", methods=["GET"])
def delete_plugin():
    output = uninstall_plugin(request.args.get("plugin_name"))
    if output == "success":
        trigger_reload()
        return "success"
    else:
        return output


@main.route("/add_repo_from_link", methods=["GET"])
def add_repo_from_link():
    add_repository(request.args.get("url"))
    return "ok"


@main.route("/delete_repository_by_id", methods=["GET"])
def delete_repository_by_id():
    repo = Repositories.query.filter_by(id=request.args.get("id")).first()
    delete_repository(repo)
    trigger_reload()
    return "ok"


@main.route("/update_repository_by_id", methods=["GET"])
def update_repository_by_id():
    repo = Repositories.query.filter_by(id=request.args.get("id")).first()
    update_repositories(repo)
    return "ok"


@main.route("/update_all_repositories", methods=["GET"])
def update_all_repositories():
    update_repositories()
    return "ok"


@main.route("/toggle_repository_auto_update", methods=["GET"])
def toggle_repository_auto_update():
    repository = Repositories.query.filter_by(id=request.args.get("repo_id")).first()
    if request.args.get("toggle") == "off":
        repository.auto_update = None
    elif request.args.get("toggle") == "on":
        repository.auto_update = True
    db.session.merge(repository)
    db.session.commit()
    return "ok"


@main.route("/install_plugin_from_repo", methods=["GET"])
def install_plugin_from_repo():
    repository = Repositories.query.filter_by(id=request.args.get("repo_id")).first()
    output = install_plugin(request.args.get("plugin_name"), repository)
    if output == "success":
        trigger_reload()
        return "success"
    else:
        return output


@main.route("/install_all_plugins_from_repo", methods=["GET"])
def install_all_plugins_from_repo():
    repository = Repositories.query.filter_by(id=request.args.get("repo_id")).first()
    repositories = get_repositories(repository)
    for plugin in repositories[0].plugins:
        reinstall_plugin(plugin["name"], repository)
    trigger_reload()
    return "ok"


@main.route("/reinstall_plugin_by_name", methods=["GET"])
def reinstall_plugin_by_name():
    repository = Repositories.query.filter_by(id=request.args.get("repo_id")).first()
    reinstall_plugin(request.args.get("plugin_name"), repository)
    trigger_reload()
    return "ok"


# ------------------------------------------------------------------------------
# TCDROP routes
# ------------------------------------------------------------------------------
@main.route("/tcdrop/cacheFile", methods=["POST"])
def cacheFile():
    f = request.files.get("file")
    ext = f.filename.split(".")[1]
    random_hex = token_hex(16)
    fn = f"{random_hex}.{ext}"
    path = os.path.join(cache_folder, fn)
    f.save(path)
    html = render_template(
        "main/tcdrop-file-row.html", orig_fn=f.filename, fn=fn, id=random_hex
    )
    file = Files(name=f.filename, path=path, cache=fn, folder="cache")
    db.session.add(file)
    db.session.commit()
    return jsonify(data={"cached": fn, "html": html})


@main.route("/tcdrop/clearCache", methods=["GET"])
def clearCache():
    files = glob.glob(cache_folder + "/*")
    for file in files:
        if ".no" not in file:
            os.remove(file)
    Files.query.filter_by(folder="cache").delete()
    db.session.commit()
    return "success"


@main.route("/tcdrop/deleteCachedFile", methods=["GET"])
def deleteCachedFile():
    f = request.args.get("file")
    path = os.path.join(cache_folder, f)
    Files.query.filter_by(path=path).delete()
    db.session.commit()
    try:
        os.remove(path)
    except FileNotFoundError:
        pass
    return "success"


# @main.route("/tcdrop/addLocalFile", methods=["GET"])
# def addLocalFile():
#     f = request.args.get("file")
#     email_cache = request.args.get("email_cache")
#     ext = f.split(".")[1]
#     random_hex = token_hex(16)
#     fn = f"{random_hex}.{ext}"
#     if email_cache == "true":
#         file = Files.query.filter_by(cache=f).first()
#         orig_fn = file.name
#         old_path = os.path.join(email_cache_folder, f)
#     else:
#         old_path = os.path.join(pdf_folder, f)
#         orig_fn = f
#     path = os.path.join(cache_folder, fn)
#     copyfile(old_path, path)
#     html = render_template(
#         "main/tcdrop-file-row.html", orig_fn=orig_fn, fn=fn, id=random_hex
#     )
#     file = Files(name=orig_fn, path=path, cache=fn, folder="cache")
#     db.session.add(file)
#     db.session.commit()
#     return jsonify(data={"file": fn, "html": html})

vectorcloud/templates/main/home.html
{% extends "layout.html" %}
{% from 'global_macros.html' import input, button %}
{% from 'main/vector-cards.html' import VectorCards with context %}

{% block page_vendor_css %}
{% endblock page_vendor_css %}

{% block page_lvl_css %}
    {{ process_css_sources(src="main/home.css")|safe }}
{% endblock page_lvl_css %}

{% block content %}
    <div id="add-repository-modal" class="modal">
        <div class="modal-content">
            <div class="row">
                <div class="col s12">
                    <h5 class="mb-3">Add Repository</h5>
                </div>
                {{ input(
                id="add-repository-repo_url",
                placeholder="https://",
                name="repo_url",
                label="Repository url",
                size="s12"
                ) }}
            </div>
        </div>
        <div class="modal-footer">
            {{ button(
            id="add-repository-clone-btn",
            data={"url": url_for('main.add_repo_from_link')},
            text="clone"
            ) }}
        </div>
    </div>
    <div id="settings-sidenav" class="sidenav">
        <div class="row mt-2">
            <div class="col s12">
                <ul class="tabs tabs-fixed-width">
                    <li class="tab col s3"><a href="#plugins-tab" class="active">
                        <span class="center-align">
                            <i class="material-icons-outlined">extension</i>
                            <span class="font-weight-900 left">Plugins</span>
                        </span>
                    </a></li>

                    <li class="tab col s3"><a href="#repositories-tab" class="active">
                        <span class="center-align">
                            <i class="material-icons-outlined">storefront</i>
                            <span class="font-weight-900 left">Repositories</span>
                        </span>
                    </a></li>

                    <li class="tab col s3"><a href="#settings-tab">
                        <span class="center-align">
                            <i class="material-icons-outlined">settings</i>
                            <span class="font-weight-900 left">Settings</span>
                        </span>
                    </a></li>

                    <li class="tab col s3"><a href="#users-tab">
                        <span class="center-align">
                            <i class="material-icons-outlined">person</i>
                            <span class="font-weight-900 left">Users</span>
                        </span>
                    </a></li>

                </ul>
            </div>
            <div id="plugins-tab" class="col s12">
                <div class="row card-filter-container">
                    <div class="col s12 input-field">
                        <span>
                            <i class="material-icons prefix card-search-icon">search</i>
                            <input type="text" id="plugins-tab-search" class="card-filter" placeholder="Search plugins">
                        </span>
                    </div>
                </div>
                {% for plugin in plugins %}
                    <div class="card theme-surface-1">
                        <div class="card-content">
                            <h4 class="plugin-name">{{ plugin['name'] }}</h4>
                            <span>{{ plugin['description'] }}</span>

                            <div class="row right-align pr-2">
                                <span class="theme-secondary-text">
                                    <i class="material-icons-outlined icon-btn tooltipped show-plugin-info-btn"
                                       data-position="top" data-tooltip="Plugin info">info</i>
{#                                    <i class="material-icons-outlined icon-btn tooltipped"#}
{#                                       data-position="top" data-tooltip="Plugin settings">settings</i>#}
                                    <i class="material-icons-outlined icon-btn tooltipped delete-plugin-btn"
                                       data-position="top" data-tooltip="Delete plugin"
                                       data-plugin="{{ plugin['name'] }}" data-url="{{ url_for('main.delete_plugin') }}">delete</i>
                                </span>
                            </div>

                            <div class="row plugin-info-row hide">
                                {% if plugin['js'] or plugin['icons'] or plugin['panels'] %}
                                    <div class="divider"></div>
                                    <h5>Provides interface</h5>
                                    {% if plugin['icons'] %}
                                        <h6>Icons</h6>
                                        {% for icon in plugin['icons'] %}
                                            {% if icon %}
                                                <text class="theme-secondary-text mb-4">
                                                    <i class="material-icons-outlined icon-btn tooltipped"
                                                       data-position="top" data-tooltip="{{ icon['tooltip'] }}">{{ icon['mdi_class'] }}</i>
                                                </text>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                    {% if plugin['panels'] %}
                                        <h6>Panels</h6>
                                        {% for panel in plugin['panels'] %}
                                            {% if panel %}
                                                <ul class="collection mb-4">
                                                    <li class="collection-item">.{{ panel['class'] }} <span class="theme-secondary-text">plugins/{{ panel['template'] }}</span></li>
                                                </ul>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                    {% if plugin['js'] %}
                                        <h6>Javascript</h6>
                                        {% for js in plugin['js'] %}
                                            {% if js %}
                                                <ul class="collection mb-4">
                                                    <li class="collection-item">static/js/plugins/{{ js }}</li>
                                                </ul>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                {% endif %}

                                {% if plugin['options'] %}
                                    <div class="divider"></div>
                                    <h5>Run Options</h5>
                                    <table class="responsive-table mb-4">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Default</th>
                                            <th>Description</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for option in plugin['options'] %}
                                            <tr>
                                                <td class="selectable-all plugin-option-name" data-plugin="{{ plugin['name'] }}">{{ option['name'] }}</td>
                                                <td>{{ option['default'] }}</td>
                                                <td>{{ option['description'] }}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                {% endif %}

                                {% if plugin['dependencies'] %}
                                    <div class="divider"></div>
                                    <h5>Plugin Dependencies</h5>
                                    {% for dependency in plugin['dependencies'] %}
                                        {% if dependency %}
                                            <ul class="collection">
                                                <li class="collection-item">{{ dependency }}</span></li>
                                            </ul>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                            </div>

                        </div>
                    </div>
                {% endfor %}
            </div>
            <div id="repositories-tab" class="col s12">
                <div class="row">
                    <div class="col s12">
                        <h4>Repositories
                            <a href="#add-repository-modal" class="modal-trigger theme-secondary-text">
                                <i class="material-icons-outlined icon-btn tooltipped"
                                   data-position="top"
                                   data-tooltip="Add repository">add
                                </i>
                            </a>
                            <i class="material-icons-outlined icon-btn tooltipped theme-secondary-text"
                               id="update-all-repositories-btn"
                               data-url="{{ url_for('main.update_all_repositories') }}"
                               data-position="top"
                               data-tooltip="Update all repositories">refresh
                            </i>
                        </h4>
                        <div class="collection" id="repositories-container" data-url="{{ url_for('main.load_repositories') }}">

                        </div>
                    </div>
                </div>
            </div>
            <div id="users-tab" class="col s12">Users</div>
            <div id="settings-tab" class="col s12">settings</div>
        </div>
    </div>

    <div id="main" class="main-full">
        <div class="container">
            <div id="vector-cards-row" class="row">
                {{ VectorCards() }}
            </div>
        </div>
    </div>

    <div id="close-settings-sidenav-btn" class="fixed-action-btn hide">
        <a class="btn-floating btn-large theme-primary">
            <i class="large material-icons">close</i>
        </a>
    </div>

    <div id="open-settings-sidenav-btn" class="fixed-action-btn">
        <a class="btn-floating btn-large theme-primary">
            <i class="large material-icons">menu_open</i>
        </a>
    </div>

{% endblock content %}

{% block page_vendor_js %}
{% endblock page_vendor_js %}

{% block page_lvl_js %}
    {{ process_js_sources(src="main/home.js")|safe }}
    {% for js_set in plugins_js %}
        {% if js_set %}
            {% for js_src in js_set %}
                {% if js_src%}
                    {{ process_js_sources(src="plugins/" + js_src)|safe }}
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endfor %}

{% endblock page_lvl_js %}

vectorcloud/templates/main/layout.html
{% extends "main/base.html" %}
{% from 'global_macros.html' import button %}

{% block page_lvl_css %}
    {{ process_css_sources(src='site_system/site.css')|safe }}
{% endblock page_lvl_css %}

{% block header %}
    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <a href="{{url_for('main.home')}}" class="brand-logo" style="margin-top: 10px"><img height="42px" src="static/images/logo/full.svg" alt="Restorely logo"/></a>
                <a href="#" data-target="nav-mobile" class="sidenav-trigger right"><i class="material-icons theme-secondary-text">menu_open</i></a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="{{url_for('main.home')}}" class="theme-primary-text">
                        <i class="material-icons-outlined tiny">home</i>
                        <b class="navbar-link-text">Home</b>
                    </a></li>
                </ul>
            </div>
        </nav>
    </div>
{% endblock header %}

{% block sidenav %}
    <ul id="nav-mobile" class="sidenav top-nav-mobile-sidenav">
        <li><a href="{{url_for('main.home')}}"><i class="material-icons-outlined">
            home</i>Home
        </a></li>
    </ul>
{% endblock sidenav %}

{% block footer %}
    {#    <footer class="page-footer footer footer-static footer-light navbar-border navbar-shadow">#}
    {#        <div class="footer-copyright">#}
    {#            <div class="container"><span>© 2019 Restorely All rights reserved.</span></div>#}
    {#        </div>#}
    {#    </footer>#}
{% endblock footer %}

vectorcloud/templates/main/repositories.html
{% for repository in repositories %}
    <div class="collection-item repository-collection-item" data-id="{{ repository.id }}">
        <h5>{{ repository.name }}
            <span class="theme-secondary-text pl-2" style="position: relative; top: 4px">
                <i class="material-icons-outlined icon-btn show-repository-plugins-btn tooltipped"
                   data-position="top" data-tooltip="Show available plugins">extension</i>

                {% if repository.auto_update %}
                    <i class="material-icons-outlined theme-primary-text icon-btn tooltipped toggle-repository-auto-update-btn"
                       data-id="{{ repository.id }}"
                       data-url="{{ url_for('main.toggle_repository_auto_update') }}"
                       data-toggle = "off"
                       data-position="top"
                       data-tooltip="Turn off auto-update">toggle_on
                    </i>
                {% else %}
                    <i class="material-icons-outlined icon-btn tooltipped toggle-repository-auto-update-btn"
                       data-id="{{ repository.id }}"
                       data-url="{{ url_for('main.toggle_repository_auto_update') }}"
                       data-toggle = "on"
                       data-position="top"
                       data-tooltip="Turn on auto-update">toggle_off
                    </i>
                {% endif %}

                <i class="material-icons-outlined icon-btn tooltipped update-repository-btn"
                   data-id="{{ repository.id }}"
                   data-url="{{ url_for('main.update_repository_by_id') }}"
                   data-position="top"
                   data-tooltip="Update repository">refresh
                </i>

                <i class="material-icons-outlined icon-btn install-all-plugins-from-repo-btn tooltipped"
                   data-url="{{ url_for('main.install_all_plugins_from_repo') }}"
                   data-id="{{ repository.id }}"
                   data-position="top"
                   data-tooltip="Install/reinstall all plugins">system_update_alt</i>

                <i class="material-icons-outlined icon-btn tooltipped delete-repository-btn"
                   data-position="top"
                   data-tooltip="Delete repository"
                   data-url="{{ url_for('main.delete_repository_by_id') }}"
                   data-id="{{ repository.id }}">delete
                </i>
            </span>
        </h5>
        <div class="collection with-header mt-2">
            <div class="collection-header">Source Code</div>
            <div class="collection-item"><a href="{{ repository.url }}" target="_blank">{{ repository.url }}</a></div>
            <div class="collection-header">Locally Stored at</div>
            <div class="collection-item"><span class="theme-secondary-text"><u>{{ repository.fp }}</u></span></div>
        </div>

        <div class="row hide repository-plugins-list">
            <div class="row card-filter-container">
                <div class="col s12 input-field">
                        <span>
                            <i class="material-icons prefix card-search-icon">search</i>
                            <input type="text" id="repository-plugins-search" class="card-filter theme-surface" placeholder="Search {{ repository.name }}">
                        </span>
                </div>
            </div>
            {% for plugin in repository.plugins %}
                <div class="card">
                    <div class="card-content">
                        <h5>{{ plugin['name'] }}</h5>
                        <h6 class="theme-secondary-text">{{ plugin['description'] }}</h6>
                        <div class="row right-align pr-2">
                            <span class="theme-secondary-text">
                                {% if plugin['installed'] == False %}
                                    <i class="material-icons-outlined theme-primary-text icon-btn tooltipped install-plugin-btn"
                                       data-position="top" data-tooltip="Install plugin"
                                       data-plugin="{{ plugin['name'] }}"
                                       data-repo_id="{{ repository.id }}"
                                       data-url="{{ url_for('main.install_plugin_from_repo') }}">get_app</i>
                                {% else %}
                                    <i class="material-icons-outlined theme-primary-text icon-btn tooltipped reinstall-plugin-from-repo-btn"
                                       data-url="{{ url_for('main.reinstall_plugin_by_name') }}"
                                       data-plugin_name="{{ plugin['name'] }}"
                                       data-repo_id="{{ repository.id }}"
                                       data-position="top"
                                       data-tooltip="Replace installed plugin {{ plugin['name'] }}">repeat</i>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>

    </div>
{% endfor %}

vectorcloud/templates/main/tcdrop-file-row.html
<li class="tcdrop-li tcdrop-file-li">
  <i class="delete-{{ id }} tcdrop-delete-file material-icons pointer"
     data-url="{{url_for('main.deleteCachedFile')}}"
     data-file="{{ fn }}"
     data-local="{{local}}">close</i>
  <span class="file-name">{{orig_fn}}</span>
</li>
<script type="text/javascript">
  $(".delete-{{ id }}").on('click', function(){
    let el = $(this).closest('.row');
    let url = $(this).attr('data-url');
    let local = $(this).attr('data-local');
    $(this).parent().remove();
    if(local === 'true'){
      let index = tcdrop_files[el.attr('id')].indexOf("{{fn}}");
      if (index > -1) {
        tcdrop_files[el.attr('id')].splice(index, 1);
      }
      tcdropHideDropArea(el)
    } else{
      $.ajax({
        url: url,
        type: 'GET',
        data: { file: $(this).attr('data-file') },
        success: function(data){
          let index = tcdrop_files[el.attr('id')].indexOf("{{fn}}");
          if (index > -1) {
            tcdrop_files[el.attr('id')].splice(index, 1);
          }
          tcdropHideDropArea(el);
        }
      });
    }
  });
</script>

vectorcloud/templates/main/tcdrop.html
{% from "global_macros.html" import preload_circle %}
{% macro tcdrop(allowed_types='all', max_files=-1, on_add="", id="", class="") %}

<!-- tcdrop html -->
<div id="{{ id }}" class="row {{ class }}">
  <form class="tcdrop-form" method="post"
        data-cache-url="{{url_for('main.cacheFile')}}"
        data-clear-cache-url="{{url_for('main.clearCache')}}"
        data-max-files="{{max_files}}",
        data-allowed-types="{{allowed_types}}">
    <input id="{{id}}-tcdrop-input" type="file" name="file" class="tcdrop tcdrop-input" onchange="{{on_add}}" multiple/>
    <label class="tcdrop-label" for="{{id}}-tcdrop-input">Drag & drop or <u>choose</u></label>
  </form>
  <ul class="tcdrop-files-ul">
    <li class="tcdrop-loading-upload hide">
      {{ preload_circle() }}
    </li>
    <li class="tcdrop-error-msg tcdrop-li hide">
      <i class="tcdrop-delete-file material-icons theme-warning">error</i>
      <span class="tcdrop-error-msg-txt file-name theme-warning-text"></span>
    </li>
  </ul>
</div>
<!-- end tcdrop html -->

{% endmacro %}