vectorcloud/main/routes.py
import os
import glob
from secrets import token_hex
from htmlmin.main import minify
from flask import (
    render_template,
    url_for,
    redirect,
    request,
    Blueprint,
    jsonify,
)
from flask_login import current_user
from vectorcloud.main.models import Files, Vectors, Repositories
from vectorcloud.main.utils import (
    run_plugin,
    get_repositories,
    get_plugins,
    uninstall_plugin,
    install_plugin,
    add_repository,
    delete_repository,
    update_repositories,
    reinstall_plugin,
    trigger_reload,
)
from vectorcloud.paths import cache_folder
from vectorcloud import app, db


main = Blueprint("main", __name__)


# ------------------------------------------------------------------------------
# intial routes and functions (before/after request)
# ------------------------------------------------------------------------------
@app.after_request
def response_minify(response):
    """
    minify html response to decrease site traffic
    """
    if response.content_type == "text/html; charset=utf-8":
        response.set_data(minify(response.get_data(as_text=True)))

        return response
    return response


# blocks access to all pages (except public routes) unless the user is
# signed in.
@main.before_app_request
def check_valid_login():

    if "/api/" in request.path:
        return
    elif current_user.is_authenticated:
        return
    elif getattr(app.view_functions[request.endpoint], "is_public", False):
        return
    elif request.endpoint.startswith("static"):
        return

    else:
        return redirect(url_for("user_system.login"))


# ------------------------------------------------------------------------------
# /home
# ------------------------------------------------------------------------------
@main.route("/")
@main.route("/home", methods=["GET", "POST"])
def home():
    vectors = Vectors.query.all()

    plugins, plugin_icons, plugin_panels, plugins_js = get_plugins()

    return render_template(
        "main/home.html",
        vectors=vectors,
        plugins=plugins,
        plugin_icons=plugin_icons,
        plugin_panels=plugin_panels,
        plugins_js=plugins_js,
        restart_needed=os.environ.get("VC_RESTART_NEEDED", None),
    )


@main.route("/load_repositories", methods=["GET"])
def load_repositories():
    repositories = get_repositories()
    return render_template("main/repositories.html", repositories=repositories)


@main.route("/run", methods=["POST"])
def run():
    options = {}
    for fieldname, value in request.form.items():
        if fieldname != "plugin_name" and len(value) >= 1:
            options[fieldname] = value
    return run_plugin(request.form.get("plugin_name"), options)


@main.route("/delete_plugin", methods=["GET"])
def delete_plugin():
    output = uninstall_plugin(request.args.get("plugin_name"))
    if output == "success":
        trigger_reload()
        return "success"
    else:
        return output


@main.route("/add_repo_from_link", methods=["GET"])
def add_repo_from_link():
    add_repository(request.args.get("url"))
    return "ok"


@main.route("/delete_repository_by_id", methods=["GET"])
def delete_repository_by_id():
    repo = Repositories.query.filter_by(id=request.args.get("id")).first()
    delete_repository(repo)
    trigger_reload()
    return "ok"


@main.route("/update_repository_by_id", methods=["GET"])
def update_repository_by_id():
    repo = Repositories.query.filter_by(id=request.args.get("id")).first()
    update_repositories(repo)
    return "ok"


@main.route("/update_all_repositories", methods=["GET"])
def update_all_repositories():
    update_repositories()
    return "ok"


@main.route("/toggle_repository_auto_update", methods=["GET"])
def toggle_repository_auto_update():
    repository = Repositories.query.filter_by(id=request.args.get("repo_id")).first()
    if request.args.get("toggle") == "off":
        repository.auto_update = None
    elif request.args.get("toggle") == "on":
        repository.auto_update = True
    db.session.merge(repository)
    db.session.commit()
    return "ok"


@main.route("/install_plugin_from_repo", methods=["GET"])
def install_plugin_from_repo():
    repository = Repositories.query.filter_by(id=request.args.get("repo_id")).first()
    output = install_plugin(request.args.get("plugin_name"), repository)
    if output == "success":
        trigger_reload()
        return "success"
    else:
        return output


@main.route("/install_all_plugins_from_repo", methods=["GET"])
def install_all_plugins_from_repo():
    repository = Repositories.query.filter_by(id=request.args.get("repo_id")).first()
    repositories = get_repositories(repository)
    for plugin in repositories[0].plugins:
        reinstall_plugin(plugin["name"], repository)
    trigger_reload()
    return "ok"


@main.route("/reinstall_plugin_by_name", methods=["GET"])
def reinstall_plugin_by_name():
    repository = Repositories.query.filter_by(id=request.args.get("repo_id")).first()
    reinstall_plugin(request.args.get("plugin_name"), repository)
    trigger_reload()
    return "ok"


# ------------------------------------------------------------------------------
# TCDROP routes
# ------------------------------------------------------------------------------
@main.route("/tcdrop/cacheFile", methods=["POST"])
def cacheFile():
    f = request.files.get("file")
    ext = f.filename.split(".")[1]
    random_hex = token_hex(16)
    fn = f"{random_hex}.{ext}"
    path = os.path.join(cache_folder, fn)
    f.save(path)
    html = render_template(
        "main/tcdrop-file-row.html", orig_fn=f.filename, fn=fn, id=random_hex
    )
    file = Files(name=f.filename, path=path, cache=fn, folder="cache")
    db.session.add(file)
    db.session.commit()
    return jsonify(data={"cached": fn, "html": html})


@main.route("/tcdrop/clearCache", methods=["GET"])
def clearCache():
    files = glob.glob(cache_folder + "/*")
    for file in files:
        if ".no" not in file:
            os.remove(file)
    Files.query.filter_by(folder="cache").delete()
    db.session.commit()
    return "success"


@main.route("/tcdrop/deleteCachedFile", methods=["GET"])
def deleteCachedFile():
    f = request.args.get("file")
    path = os.path.join(cache_folder, f)
    Files.query.filter_by(path=path).delete()
    db.session.commit()
    try:
        os.remove(path)
    except FileNotFoundError:
        pass
    return "success"


# @main.route("/tcdrop/addLocalFile", methods=["GET"])
# def addLocalFile():
#     f = request.args.get("file")
#     email_cache = request.args.get("email_cache")
#     ext = f.split(".")[1]
#     random_hex = token_hex(16)
#     fn = f"{random_hex}.{ext}"
#     if email_cache == "true":
#         file = Files.query.filter_by(cache=f).first()
#         orig_fn = file.name
#         old_path = os.path.join(email_cache_folder, f)
#     else:
#         old_path = os.path.join(pdf_folder, f)
#         orig_fn = f
#     path = os.path.join(cache_folder, fn)
#     copyfile(old_path, path)
#     html = render_template(
#         "main/tcdrop-file-row.html", orig_fn=orig_fn, fn=fn, id=random_hex
#     )
#     file = Files(name=orig_fn, path=path, cache=fn, folder="cache")
#     db.session.add(file)
#     db.session.commit()
#     return jsonify(data={"file": fn, "html": html})

vectorcloud/user_system/routes.py
import subprocess
import os
from flask import render_template, url_for, redirect, Blueprint, jsonify, request
from flask_login import login_user, logout_user
from vectorcloud.user_system.forms import LoginForm, RegisterForm, VectorForm
from vectorcloud.user_system.models import User
from vectorcloud.user_system.utils import add_user_func
from vectorcloud import bcrypt
from vectorcloud.main.utils import public_route, trigger_reload
from vectorcloud.main.models import Vectors
from vectorcloud.user_system.authenticate_vector import main as authenticate_vector
from vectorcloud.paths import vc_folder

user_system = Blueprint("user_system", __name__)


# ------------------------------------------------------------------------------
# User system routes
# ------------------------------------------------------------------------------
# onboarding
@public_route
@user_system.route("/onboarding", methods=["GET", "POST"])
def onboarding():
    user = User.query.first()
    vector = Vectors.query.first()
    register_form = RegisterForm()
    vector_form = VectorForm()
    return render_template(
        "user/onboarding.html",
        title="Onboarding",
        register_form=register_form,
        vector_form=vector_form,
        user=user,
        vector=vector,
    )


# login page
@public_route
@user_system.route("/login", methods=["GET", "POST"])
def login():
    if not User.query.first() or not Vectors.query.first():
        return redirect(url_for("user_system.onboarding"))
    form = LoginForm()
    return render_template("user/login.html", title="Login", form=form)


@public_route
@user_system.route("/check_login", methods=["POST"])
def check_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data.lower()).first()
        if not user:
            response = {"err": "User not found"}

        elif bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            response = {"url": url_for("main.home")}
        else:
            response = {"err": "Password is wrong"}
    else:
        response = {"err": str(form.errors)}

    return jsonify(data=response)


# this logs the user out and redirects to the login page
@user_system.route("/logout")
def logout():

    logout_user()
    return redirect(url_for("user_system.login"))


@public_route
@user_system.route("/welcome")
def welcome():
    register_form = RegisterForm()
    return render_template(
        "user/welcome.html", title="Welcome", register_form=register_form
    )


@public_route
@user_system.route("/add_user", methods=["POST"])
def add_user():
    form = RegisterForm()
    if form.validate_on_submit():
        user = add_user_func(request.form.get("username"), request.form.get("password"))
        login_user(user)
        return jsonify(data={"err": "success", "url": url_for("main.home")})
    else:
        return jsonify(data={"err": str(form.errors)})


@public_route
@user_system.route("/add_vector", methods=["POST"])
def add_vector():
    anki_email = request.form.get("anki_email")
    anki_password = request.form.get("anki_password")
    ip = request.form.get("ip")
    name = request.form.get("name")
    serial = request.form.get("serial")
    cmd = f'python3 -m vectorcloud.user_system.anki_configure -e "{anki_email}" -p "{anki_password}" -i "{ip}" -n "{name}" -s "{serial}"'
    output = subprocess.run(cmd, capture_output=True, shell=True, text=True)
    if "SUCCESS!" in output.stdout:
        success = "true"
        trigger_reload()
    else:
        success = "false"
    return jsonify(
        data={"output": output.stdout.replace("\n", "<br>"), "success": success}
    )

vectorcloud/templates/user/login.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col s12 l4 offset-l4">
            <div class="card">
                <div class="card-content">
                    <div class="row center-align mt-4">
                        <img width="120px" src="static/images/logo/logo.svg" alt="VectorCloud Logo">
                    </div>
                    <div class="row">
                        <form class="login-form" method="POST" data-url="{{ url_for('user_system.check_login') }}">
                            {{ form.hidden_tag() }}

                            <div class="input-field col s12">
                                <i class="material-icons-outlined prefix">person</i>
                                {{ form.username(class="validate", id="username", type="text") }}
                                <label for="username" class="center-align">Username</label>
                            </div>

                            <div class="input-field col s12">
                                <i class="material-icons-outlined prefix">lock_outline</i>
                                {{ form.password(class="validate", id="password", type="password") }}
                                <label for="password">Password</label>
                            </div>

                            <div class="switch">
                                <label>
                                    {{ form.remember(type="checkbox", checked="true") }}
                                    <span class="lever"></span>
                                    Remember Me
                                </label>
                            </div>


                            <div class="input-field col s12">
                                <button type=submit class="btn theme-primary waves-effect waves-light right">Sign in</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block page_lvl_js %}
    {{ process_js_sources(src="user_system/login.js")|safe }}
{% endblock page_lvl_js %}

vectorcloud/templates/user/onboarding.html
{% extends "base.html" %}
{% from 'global_macros.html' import input, button %}

{% block content %}
    <style>
        body {
            overflow: auto !important;
        }
    </style>
    <div id="user-exists" class="hide" data-home-url="{{ url_for('main.home') }}">{{ user }}</div>
    <div id="vector-exists" class="hide">{{ vector }}</div>
    <div class="row add-user-row">
        <div class="col s12 l4 offset-l4">
            <div class="card">
                <div class="card-content">
                    <div class="row center-align mt-4">
                        <img width="120px" src="static/images/logo/logo.svg" alt="VectorCloud Logo">
                    </div>
                    <div class="row center-align">
                        <h4>Welcome to VectorCloud!</h4>
                        <blockquote>VectorCloud is an open-source platform for interacting with your Vector robot! Please create a user account below to get started.</blockquote>
                    </div>
                    <div class="row">
                        <form class="register-form" method="POST" data-url="{{ url_for('user_system.add_user') }}">
                            {{ register_form.hidden_tag() }}

                            {{ input(
                            form_obj=register_form.username,
                            id="register-form-username",
                            size="s12",
                            icon="person",
                            label="Username"
                            ) }}

                            {{ input(
                            form_obj=register_form.password,
                            id="register-form-password",
                            size="s12",
                            icon="lock",
                            label="Password"
                            ) }}

                            {{ input(
                            form_obj=register_form.confirm_password,
                            id="register-form-confirm_password",
                            size="s12",
                            icon="lock",
                            label="Confirm Password"
                            ) }}

                            <div class="input-field col s12">
                                <button type=submit class="btn theme-primary waves-effect waves-light right">Register</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row add-vector-row hide">
        <div class="col s12 l6 offset-l3">
            <div class="card">
                <div class="card-content">
                    <div class="row center-align">
                        <h5>No SDK configuration found.</h5>
                        <blockquote>It looks like you haven't set up the SDK with any vectors on this device. Don't worry, VectorCloud can help with that.</blockquote>
                    </div>
                    <div id="sdk-config-error-row" class="row hide theme-warning white-text padding-2 border-radius-10 mb-2"></div>
                    <div class="row">
                        <div id="add-vector-form-code-card" class=" hide card col s12 theme-surface-1">
                            <div class="card-content">
                                <code id="add-vector-form-code" style="font-size: .8rem">
                                    Using robot name: Vector-V9T3 <br>
                                    Using IP: 192.168.39.188 <br>
                                    Using robot serial number: 00306af0 <br>
                                    Downloading Vector certificate from Anki... <br>
                                    Writing certificate file to '/home/ross/.anki_vector/Vector-V9T3-00306af0.cert'... <br>
                                    Attempting to download guid from Vector-V9T3 at 192.168.39.188:443... <br>
                                    Done. <br>
                                    Writing config file to '/home/ross/.anki_vector/sdk_config.ini'... <br>
                                </code>
                            </div>
                        </div>
                        <form class="vector-form" method="POST" data-url="{{ url_for('user_system.add_vector') }}">
                            {{ vector_form.hidden_tag() }}

                            {{ button(
                            text="Go to homepage",
                            icon="home",
                            id="go-to-home-btn",
                            class="hide",
                            href=url_for('main.home')
                            ) }}

                            {{ input(
                            form_obj=vector_form.anki_email,
                            id="vector-form-anki_email",
                            size="s12",
                            label="Anki Email"
                            ) }}

                            {{ input(
                            form_obj=vector_form.anki_password,
                            id="register-form-anki_password",
                            size="s12",
                            label="Anki Password"
                            ) }}

                            {{ input(
                            form_obj=vector_form.name,
                            id="register-form-name",
                            size="s12",
                            label="Vector Name (e.g. Vector-W2R3)"
                            ) }}

                            {{ input(
                            form_obj=vector_form.ip,
                            id="register-form-ip",
                            size="s12",
                            label="Vector IP"
                            ) }}

                            {{ input(
                            form_obj=vector_form.serial,
                            id="register-form-serial",
                            size="s12",
                            label="Vector Serial"
                            ) }}

                            <div class="input-field col s12">
                                <button id="submit-vector-form-btn" type=submit class="btn theme-primary waves-effect waves-light right">Authenticate</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block page_lvl_js %}
    {{ process_js_sources(src="user_system/onboarding.js")|safe }}
{% endblock page_lvl_js %}

vectorcloud/templates/user/register.html
{% extends "base.html" %}
{% from 'global_macros.html' import input, button %}
{% block content %}
    <div class="row">
        <div class="card col s12 m12 l4 offset-l4">
            <h5>Register</h5>

            <form id="register-form">
                {{input(
                id="register-fname",
                label="First Name",
                form_obj=form.fname,
                class="",
                size="s6"
                )}}

                {{input(
                id="register-lname",
                label="Last Name",
                form_obj=form.lname,
                class="",
                size="s6"
                )}}

                {{input(
                id="register-email",
                label="Email",
                form_obj=form.email,
                class="",
                size="s12"
                )}}

                {{input(
                id="register-password",
                label="Password",
                form_obj=form.password,
                class="",
                size="s12"
                )}}

                {{input(
                id="register-confirm-password",
                label="Confirm Password",
                form_obj=form.confirm_password,
                class="",
                size="s12"
                )}}

                {{button(
                text="submit",
                id="register-submit-btn",
                class="mb-2",
                data={'url': url_for('user_system.add_user'),
                      'done-url': url_for('user_system.login')}
                )}}
            </form>

        </div>
    </div>

    <script>
        $("#register-submit-btn").on('click', function(e) {
            var done_url = $(this).attr('data-done-url')
            $.ajax({
                url: $(this).attr('data-url'),
                type: 'POST',
                data: $("#register-form").serialize(),
                success: function(data){
                    $(location).attr('href', done_url);
                }
            });
        });
    </script>
{% endblock content %}

vectorcloud/templates/user/welcome.html
{% extends "base.html" %}
{% from 'global_macros.html' import input, button %}
{% block content %}
    <div class="row">
        <div class="card col s12 m12 l4 offset-l4">
            <h5>Register</h5>

            <form id="register-form">
                {{input(
                id="register-fname",
                label="First Name",
                form_obj=register_form.fname,
                class="",
                size="s6"
                )}}

                {{input(
                id="register-lname",
                label="Last Name",
                form_obj=register_form.lname,
                class="",
                size="s6"
                )}}

                {{input(
                id="register-email",
                label="Email",
                form_obj=register_form.email,
                class="",
                size="s12"
                )}}

                {{input(
                id="register-password",
                label="Password",
                form_obj=register_form.password,
                class="",
                size="s12"
                )}}

                {{input(
                id="register-confirm-password",
                label="Confirm Password",
                form_obj=register_form.confirm_password,
                class="",
                size="s12"
                )}}

                {{button(
                text="submit",
                id="register-submit-btn",
                class="mb-2",
                data={'url': url_for('user_system.add_user'),
                      'done-url': url_for('user_system.login')}
                )}}
            </form>

        </div>
    </div>

    <script>
        $("#register-submit-btn").on('click', function(e) {
            var done_url = $(this).attr('data-done-url')
            $.ajax({
                url: $(this).attr('data-url'),
                type: 'POST',
                data: $("#register-form").serialize(),
                success: function(data){
                    $(location).attr('href', done_url);
                }
            });
        });
    </script>
{% endblock content %}